### ISSUE TITLE
Incorporate documentation of digest file into GitBook

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/gitbook-kontrol#44]
@asavienko and @anvacaru produced this document describing the digest files. We should incorporate it as part of our developer documentation: https://docs.google.com/document/d/18HEqdVx2pi2tRjq-4GvYy80I4RuEgHxwQX2zniHEAfo/edit

**Comment by palinatolmach** [comment]
Thanks @asavienko and @anvacaru! I opened a PR in GitBook (https://github.com/runtimeverification/gitbook-kontrol/pull/45) adding it as an `md` file to a new `Developer Docs` section.

One minor recommendation wrt to the docs going forward is to use permalinks with a fixed commit instead of a URL referencing the `master` branch:

`https://github.com/runtimeverification/kontrol/blob/b7065f74304e7af9a43506849331fd6b73039ccb/src/kontrol/solc_to_k.py#L359`
vs
`https://github.com/runtimeverification/kontrol/blob/master/src/kontrol/solc_to_k.py#L359`.

That would help ensure that lines we're pointing to in the documentation or articles won't change when the code gets updated.
